resources:
- repo: self

pool:
  vmImage: ubuntu-16.04

trigger: [master]

steps:
- script: |
    git config --global credential.helper osxkeychain
    sudo npm install hexo-cli -g
    sudo npm install 
    sudo hexo g -d


