resources:
- repo: self

pool:
  vmImage: ubuntu-16.04

trigger: [master]

steps:
- script: |
    git config --global user.name "635253084@qq.com"
    sudo npm install hexo-cli -g
    sudo npm install 
    sudo hexo g -d


